//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TropicalServer.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.autoCompleteSoap")]
    public interface autoCompleteSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TropicalServer.ServiceReference1.HelloWorldResponse HelloWorld(TropicalServer.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name word from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAutoCompleteName", ReplyAction="*")]
        TropicalServer.ServiceReference1.getAutoCompleteNameResponse getAutoCompleteName(TropicalServer.ServiceReference1.getAutoCompleteNameRequest request);
        
        // CODEGEN: Generating message contract since element name word from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAutoCompleteName2", ReplyAction="*")]
        TropicalServer.ServiceReference1.getAutoCompleteName2Response getAutoCompleteName2(TropicalServer.ServiceReference1.getAutoCompleteName2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TropicalServer.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TropicalServer.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TropicalServer.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TropicalServer.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAutoCompleteNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAutoCompleteName", Namespace="http://tempuri.org/", Order=0)]
        public TropicalServer.ServiceReference1.getAutoCompleteNameRequestBody Body;
        
        public getAutoCompleteNameRequest() {
        }
        
        public getAutoCompleteNameRequest(TropicalServer.ServiceReference1.getAutoCompleteNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAutoCompleteNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string word;
        
        public getAutoCompleteNameRequestBody() {
        }
        
        public getAutoCompleteNameRequestBody(string word) {
            this.word = word;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAutoCompleteNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAutoCompleteNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public TropicalServer.ServiceReference1.getAutoCompleteNameResponseBody Body;
        
        public getAutoCompleteNameResponse() {
        }
        
        public getAutoCompleteNameResponse(TropicalServer.ServiceReference1.getAutoCompleteNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAutoCompleteNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TropicalServer.ServiceReference1.ArrayOfString getAutoCompleteNameResult;
        
        public getAutoCompleteNameResponseBody() {
        }
        
        public getAutoCompleteNameResponseBody(TropicalServer.ServiceReference1.ArrayOfString getAutoCompleteNameResult) {
            this.getAutoCompleteNameResult = getAutoCompleteNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAutoCompleteName2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAutoCompleteName2", Namespace="http://tempuri.org/", Order=0)]
        public TropicalServer.ServiceReference1.getAutoCompleteName2RequestBody Body;
        
        public getAutoCompleteName2Request() {
        }
        
        public getAutoCompleteName2Request(TropicalServer.ServiceReference1.getAutoCompleteName2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAutoCompleteName2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string word;
        
        public getAutoCompleteName2RequestBody() {
        }
        
        public getAutoCompleteName2RequestBody(string word) {
            this.word = word;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAutoCompleteName2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAutoCompleteName2Response", Namespace="http://tempuri.org/", Order=0)]
        public TropicalServer.ServiceReference1.getAutoCompleteName2ResponseBody Body;
        
        public getAutoCompleteName2Response() {
        }
        
        public getAutoCompleteName2Response(TropicalServer.ServiceReference1.getAutoCompleteName2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAutoCompleteName2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TropicalServer.ServiceReference1.ArrayOfString getAutoCompleteName2Result;
        
        public getAutoCompleteName2ResponseBody() {
        }
        
        public getAutoCompleteName2ResponseBody(TropicalServer.ServiceReference1.ArrayOfString getAutoCompleteName2Result) {
            this.getAutoCompleteName2Result = getAutoCompleteName2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface autoCompleteSoapChannel : TropicalServer.ServiceReference1.autoCompleteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class autoCompleteSoapClient : System.ServiceModel.ClientBase<TropicalServer.ServiceReference1.autoCompleteSoap>, TropicalServer.ServiceReference1.autoCompleteSoap {
        
        public autoCompleteSoapClient() {
        }
        
        public autoCompleteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public autoCompleteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public autoCompleteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public autoCompleteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TropicalServer.ServiceReference1.HelloWorldResponse TropicalServer.ServiceReference1.autoCompleteSoap.HelloWorld(TropicalServer.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TropicalServer.ServiceReference1.HelloWorldRequest inValue = new TropicalServer.ServiceReference1.HelloWorldRequest();
            inValue.Body = new TropicalServer.ServiceReference1.HelloWorldRequestBody();
            TropicalServer.ServiceReference1.HelloWorldResponse retVal = ((TropicalServer.ServiceReference1.autoCompleteSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TropicalServer.ServiceReference1.getAutoCompleteNameResponse TropicalServer.ServiceReference1.autoCompleteSoap.getAutoCompleteName(TropicalServer.ServiceReference1.getAutoCompleteNameRequest request) {
            return base.Channel.getAutoCompleteName(request);
        }
        
        public TropicalServer.ServiceReference1.ArrayOfString getAutoCompleteName(string word) {
            TropicalServer.ServiceReference1.getAutoCompleteNameRequest inValue = new TropicalServer.ServiceReference1.getAutoCompleteNameRequest();
            inValue.Body = new TropicalServer.ServiceReference1.getAutoCompleteNameRequestBody();
            inValue.Body.word = word;
            TropicalServer.ServiceReference1.getAutoCompleteNameResponse retVal = ((TropicalServer.ServiceReference1.autoCompleteSoap)(this)).getAutoCompleteName(inValue);
            return retVal.Body.getAutoCompleteNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TropicalServer.ServiceReference1.getAutoCompleteName2Response TropicalServer.ServiceReference1.autoCompleteSoap.getAutoCompleteName2(TropicalServer.ServiceReference1.getAutoCompleteName2Request request) {
            return base.Channel.getAutoCompleteName2(request);
        }
        
        public TropicalServer.ServiceReference1.ArrayOfString getAutoCompleteName2(string word) {
            TropicalServer.ServiceReference1.getAutoCompleteName2Request inValue = new TropicalServer.ServiceReference1.getAutoCompleteName2Request();
            inValue.Body = new TropicalServer.ServiceReference1.getAutoCompleteName2RequestBody();
            inValue.Body.word = word;
            TropicalServer.ServiceReference1.getAutoCompleteName2Response retVal = ((TropicalServer.ServiceReference1.autoCompleteSoap)(this)).getAutoCompleteName2(inValue);
            return retVal.Body.getAutoCompleteName2Result;
        }
    }
}
